INSERT INTO EMPLOYEE(ID, NAME, DEPARTMENT, ROLE) values(1,'nagarjuna karuturi', 1, 'SOFTWARE ENGINEER');
INSERT INTO EMPLOYEE(ID, NAME, DEPARTMENT, ROLE) values(2,'riya karuturi', 0, 'EXECUTIVE STAFF');
INSERT INTO EMPLOYEE(ID, NAME, DEPARTMENT, ROLE) values(3,'kavya putumbaka', 2, 'SR ENGINEER');
INSERT INTO EMPLOYEE(ID, NAME, DEPARTMENT, ROLE) values(4,'sruthi karuturi', 2, 'SR DEVELOPER');
INSERT INTO EMPLOYEE(ID, NAME, DEPARTMENT, ROLE) values(5,'prakarsha akula', 1, 'SR UI DEVELOPER');